Extend DSL for surrogate endpoints and transportability
y0-causal-inference/y0 pull request #149
Opened 2023-07-20 17:47 UTC by cthoyt

This PR extends the DSL with several elements to support surrogate endpoints and transportability. In particular it adds:

1. An extension of the `Probability` class called `PopulationProbability` which has an additional `population: Variable` attribute
2. A new `PopulationProbability` builder, which can be used like
    ```python
    from y0.dsl import PP, Pi1, Y, X

    # Make a population-annotated probability of Y
    >>> PP[Pi1](Y)

    # Make a conditioned population of Y @ X
    >>> PP[Pi1][X](Y)
    ```

2023-07-28 20:47 UTC, djinnome requested changes
Looks good, but I would recommend that in `find_transport_vertices` and `add_transportability_nodes`, the parameters should be renamed from `Zi` to `intervention` and `Wi` to `surrogate_outcome`

Likewise, in `surrogate_to_transport` I would recommend `Y` be `target_outcomes`, `X` be `target_interventions`, `Z` be `surrogate_interventions`, and `W` be `surrogate_outcomes`

2023-08-11 13:26 UTC, cthoyt commented on src/y0/algorithm/transport.py
> +    # Find the c_component with surrogate_outcomes
is there a case for this being a more generic function for finding the "c-component" for multiple nodes?

We can also implement this upside down:

```python
    c_component_surrogate_outcomes: Set[Variable] = set()
    for o in surrogate_outcomes:
        c_component_surrogate_outcomes.update(graph.get_district(outcome))
```

2023-08-11 13:37 UTC, cthoyt commented on src/y0/algorithm/transport.py
> +    Ancestors_surrogate_outcomes = interventions_overbar.ancestors_inclusive(surrogate_outcomes)
What is the name of the operation:

```python
graph.remove_in_edges(interventions).ancestors_inclusive(outcomes)
```

This appears several places. I think it would save some space to give it a nice name and make it a graph-level function

2023-09-06 08:23 UTC, cthoyt commented on src/y0/algorithm/transport.py
> +.. todo::
writing documentation required for merging!

2023-09-13 16:33 UTC, merged