Adding evans fourth simplification rule and test cases for network si…
y0-causal-inference/y0 pull request #191
Opened 2023-10-27 18:20 UTC by pnavada

…mplification

2023-10-27 22:22 UTC, cthoyt commented on src/y0/algorithm/simplify_latent.py
> -.. seealso:: https://www.fields.utoronto.ca/programs/scientific/11-12/graphicmodels/Evans.pdf slides 34-43
This change doesn’t make sense, it breaks the documentation seealso directive

2023-10-27 22:23 UTC, cthoyt commented on src/y0/algorithm/simplify_latent.py
> -        new_node = Variable(f"{latent_node}{suffix}")
Is this change necessary to make this Pr work? Otherwise it’s a distracting stylistic change that should be in a different pr

2023-10-28 09:55 UTC, cthoyt requested changes
I made a couple modifications:

1. Reverted stylistic changes to labeling of latent nodes
2. Reverted spurious code changes
3. Fixed usages of NxMixedGraph vs LV-DAG (nx.DiGraph) in the tests


What this PR needs to finish:

1. Better documentation on each integration test for `simplify_latent_dag` (i.e., in the docstring for each, explain which condition is being tested)
2. The tests have to pass. I can't imagine why these started failing just after reverting some stylistic information about the node names other than something is relying on the node names in a way it should not

2023-11-05 22:16 UTC, cthoyt commented
@pnavada thanks for the updates, if this is ready, please let me know and I can merge

2023-11-05 22:28 UTC, pnavada commented
Yes, its ready to merge

2023-11-05 22:35 UTC, merged